/**
 * Two people, two independent sessions, one incident.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS FILE IS AND IS NOT EVIDENCE FOR
 * ---------------------------------------------------------------------------
 *
 * An independent review asked for proof that a change made by one signed-in
 * person reaches another person's ALREADY-OPEN screen, with no navigation and
 * no manual refresh. A sequential logout/login test cannot prove that: one
 * session at a time never has to deliver anything to anybody.
 *
 * So: two `browser.newContext()` contexts, each with its own cookie jar, its
 * own `localStorage` and its own Supabase session. Context A is signed in as a
 * COMMANDER, context B as a FIREFIGHTER, both screens are opened BEFORE any
 * mutation, and neither page is navigated or reloaded for the rest of the test.
 * Two tabs of one browser would have shared a session and proved nothing.
 *
 * The server behind them is `e2e/live-project.ts`: one mutable store, and a
 * Realtime socket that really speaks the Phoenix protocol, so the application's
 * own `useLiveOperations` reports LIVE rather than falling back to a timer.
 * Every step below asserts on the LIVE state first - a test that accepted
 * POLLING would pass with the socket broken and would only be measuring a
 * twelve-second interval.
 *
 * **This is not the hosted project.** CI holds no credentials for it and must
 * not; these tests contact nothing real. What they prove is the client and the
 * propagation contract. Two things are deliberately left to the product owner
 * and named in `docs/DEMO_RUNBOOK.md`:
 *
 *   1. the same fifteen steps against hosted Supabase, signed in as two real
 *      accounts, and
 *   2. the same fifteen steps on two PHYSICAL devices on different networks.
 *
 * Neither is claimed here.
 */

import { expect, test, type Browser, type Page } from '@playwright/test';
import {
  COMMANDER,
  COMMANDER_MEMBER,
  createLiveProject,
  FIREFIGHTER,
  FIREFIGHTER_MEMBER,
  type LiveProject,
} from './live-project';

const APP = 'http://127.0.0.1:4174';

/** Long enough for a socket frame and the hook's 350 ms settle, never for a 12 s poll. */
const REALTIME_BUDGET = 6_000;

interface Pair {
  readonly project: LiveProject;
  readonly commander: Page;
  readonly firefighter: Page;
  close(): Promise<void>;
}

/**
 * Two independent contexts, both already looking at their screens.
 *
 * Everything after this point happens without touching the address bar.
 */
async function twoPeople(browser: Browser): Promise<Pair> {
  const project = createLiveProject();

  const contextA = await browser.newContext();
  const contextB = await browser.newContext();
  await project.install(contextA, COMMANDER);
  await project.install(contextB, FIREFIGHTER);

  const commander = await contextA.newPage();
  const firefighter = await contextB.newPage();

  await commander.goto(`${APP}/#/poziv`);
  await firefighter.goto(`${APP}/#/mobilizacija`);
  await commander.waitForSelector('main');
  await firefighter.waitForSelector('main');

  return {
    project,
    commander,
    firefighter,
    close: async () => {
      await contextA.close();
      await contextB.close();
    },
  };
}

/**
 * Picks the draft whose title contains `text` out of the intervention selector.
 *
 * The console keeps whatever intervention was already selected when a new draft
 * is saved, so choosing the new one is a real step a commander takes - not a
 * workaround. Matched on the option's own text because the id is generated by
 * the server.
 */
async function selectDraft(page: Page, text: string): Promise<void> {
  const picker = page.getByTestId('intervention-picker');
  await expect(picker.locator('option', { hasText: text })).toHaveCount(1, { timeout: 10_000 });
  const value = await picker.locator('option', { hasText: text }).getAttribute('value');
  await picker.selectOption(value ?? '');
}

/** Both screens must be genuinely subscribed before anything is asserted about delivery. */
async function bothLive(pair: Pair): Promise<void> {
  for (const page of [pair.commander, pair.firefighter]) {
    await expect(
      page.getByTestId('live-state'),
      'a screen on a timer would make every assertion below a test of the timer',
    ).toHaveAttribute('data-live', 'LIVE', { timeout: 20_000 });
    await expect(page.getByTestId('live-state')).toContainText(/uzivo/i);
  }
}

test.describe('two independent sessions, no navigation and no manual refresh', () => {
  test.describe.configure({ mode: 'serial' });

  test('the fifteen steps of a call-out reach the other screen by themselves', async ({ browser }) => {
    test.slow();
    const pair = await twoPeople(browser);
    const { commander, firefighter } = pair;

    try {
      await bothLive(pair);

      // ---------------------------------------------------------------- 1
      // The commander publishes. Typed into the form on the open screen,
      // exactly as a person would.
      await commander.getByTestId('new-title').fill('Vjezba: dvostruka provjera (izmisljeno)');
      await commander.getByTestId('new-instructions').fill('Okupljanje u bazi.');
      await commander.getByTestId('new-location').fill('Poligon (izmisljena lokacija)');
      await commander.getByTestId('create-draft').click();
      // Select the draft that was just saved. The console keeps whatever was
      // selected, so a person picks the new one here exactly as the test does.
      await selectDraft(commander, 'dvostruka provjera');
      await expect(commander.getByTestId('recipient-picker')).toBeVisible();
      await commander
        .getByTestId('recipient-picker')
        .locator('li', { hasText: FIREFIGHTER.name })
        .getByRole('checkbox')
        .check();
      await commander.getByTestId('publish').click();
      await commander.getByRole('button', { name: 'Objavi', exact: true }).click();

      // ---------------------------------------------------------------- 2
      // The firefighter's screen was never touched and shows the call-out.
      await expect(
        firefighter.getByRole('heading', { name: /dvostruka provjera/ }),
        'a published call-out must arrive on an open screen by itself',
      ).toBeVisible({ timeout: REALTIME_BUDGET });

      // ---------------------------------------------------------------- 3
      await firefighter.getByTestId('acknowledge').click();
      await expect(firefighter.getByTestId('ack-state')).toBeVisible();

      // ---------------------------------------------------------------- 4
      // The commander sees the opening AND how long it took, without moving.
      await commander.getByRole('tab', { name: 'Pregled' }).click();
      const row = commander.getByTestId(`timing-row-${FIREFIGHTER_MEMBER}`);
      await expect(row).toContainText('Nije zabiljezeno'); // nothing answered yet
      await expect(row, 'the opening must arrive on its own').not.toContainText(
        /Otvaranje\s*Vrijeme\s*Nije zabiljezeno/,
        { timeout: REALTIME_BUDGET },
      );
      await expect(
        commander.getByTestId('first-open'),
        'and the timing with it',
      ).toContainText(/\d+ s|\d+ min/, { timeout: REALTIME_BUDGET });

      // ---------------------------------------------------------------- 5
      await firefighter.getByTestId('answer-DOLAZIM').click();
      await firefighter.getByTestId('submit-answer').click();

      // ---------------------------------------------------------------- 6
      await expect(row, 'the answer must arrive without a refresh').toContainText(
        'Dolazim',
        { timeout: REALTIME_BUDGET },
      );
      await expect(commander.getByTestId('first-coming')).toContainText(/\d+ s|\d+ min/);

      // ---------------------------------------------------------------- 7
      // Each movement separately, in order, all three visible to the commander.
      for (const step of ['KRECEM', 'U_PUTU', 'NA_LICU_MJESTA']) {
        await firefighter.getByTestId(`journey-${step}`).click();
      }
      await expect(row, 'Krecem').toContainText('Krecem', { timeout: REALTIME_BUDGET });
      await expect(row, 'U putu').toContainText('U putu');
      await expect(row, 'Na licu mjesta').toContainText('Na licu mjesta');
      await expect(commander.getByTestId('first-arrive')).toContainText(/\d+ s|\d+ min/);

      // ---------------------------------------------------------------- 8
      await firefighter.getByTestId('check-in').click();
      await expect(row, 'the check-in must arrive').toContainText('Prijava', {
        timeout: REALTIME_BUDGET,
      });
      await expect(commander.getByTestId('first-checkin')).toContainText(/\d+ s|\d+ min/);

      // ---------------------------------------------------------------- 9
      // Checked out and confirmed by the commander, which is the only thing
      // that turns a claim into participation.
      await firefighter.getByTestId('check-out').click();
      await commander.getByRole('tab', { name: 'Prisustvo' }).click();
      await expect(
        commander.getByTestId('pending-list'),
        'the claim must reach the commander without a refresh',
      ).toContainText(FIREFIGHTER.name, { timeout: REALTIME_BUDGET });
      await commander.getByTestId('pick-all-pending').click();
      await commander.getByTestId('confirm-many').click();

      // --------------------------------------------------------------- 10
      // The firefighter sees their own record become confirmed, unprompted.
      await expect(
        firefighter.getByTestId('my-intervals'),
        'the confirmation must reach the member who made the claim',
      ).toContainText('Potvrdjeno', { timeout: REALTIME_BUDGET });

      // --------------------------------------------------------------- 11
      await commander.getByRole('tab', { name: 'Vozila' }).click();
      const vehicle = commander.getByTestId('vehicle-NV-1');
      await expect(vehicle).toHaveText('Zabiljezi izlazak');
      await vehicle.click();
      // The same button becomes the return once the server has the departure -
      // which is itself proof the change came back through a re-read.
      await expect(vehicle).toHaveText('Zabiljezi povratak', { timeout: REALTIME_BUDGET });
      await vehicle.click();
      await expect(vehicle).toHaveText('Zabiljezi izlazak', { timeout: REALTIME_BUDGET });

      // --------------------------------------------------------------- 12
      // State transitions, each one its own recorded event.
      await commander.getByRole('tab', { name: 'Poziv' }).click();
      for (const status of ['ASSEMBLING', 'DEPLOYED', 'CONTAINED']) {
        await commander.getByTestId(`status-${status}`).click();
      }

      // --------------------------------------------------------------- 13
      await commander.getByTestId('close-intervention').click();
      await commander.getByTestId('close-reason').fill('Vjezba zavrsena - test operativnog prototipa.');
      await commander.getByRole('button', { name: 'Zatvori', exact: true }).click();

      // --------------------------------------------------------------- 14
      // Both screens reflect the closure without either being navigated.
      await expect(
        firefighter.getByText(/zatvoren|Zatvoreno/i).first(),
        'the closure must reach the firefighter too',
      ).toBeVisible({ timeout: REALTIME_BUDGET });

      // --------------------------------------------------------------- 15
      // And the record is in the archive, with the durations, when it is opened.
      await commander.goto(`${APP}/#/arhiva`);
      await expect(commander.getByTestId('archive-record')).toBeVisible();
      await expect(commander.getByTestId('total-duration')).not.toContainText('Nije zabiljezeno');
      await expect(commander.getByTestId('vehicle-periods')).toBeVisible();
      await expect(
        commander.getByTestId('vehicle-periods'),
        'the vehicle duration the archive never printed',
      ).toContainText(/\d+ s|\d+ min|\d+ h/);
      const timeline = commander.getByTestId('archive-timeline');
      await expect(timeline, 'the closing note, quoted without a second full stop')
        .not.toContainText('prototipa..');
      await expect(timeline).toContainText('Vjezba zavrsena');

      // Every movement is its own audit line, not just the latest.
      const lines = await timeline.locator('li').allTextContents();
      const movements = lines.filter((line) => /javio kretanje/.test(line));
      expect(movements, 'three movements were reported and three must be recorded').toHaveLength(3);
    } finally {
      await pair.close();
    }
  });

  test('a dropped socket recovers the event it missed', async ({ browser }) => {
    test.slow();
    const pair = await twoPeople(browser);
    const { commander, firefighter, project } = pair;

    try {
      await bothLive(pair);

      // Publish first, so there is something both screens are watching.
      await commander.getByTestId('new-title').fill('Vjezba: prekid veze (izmisljeno)');
      await commander.getByTestId('new-instructions').fill('Okupljanje u bazi.');
      await commander.getByTestId('new-location').fill('Poligon (izmisljena lokacija)');
      await commander.getByTestId('create-draft').click();
      await selectDraft(commander, 'prekid veze');
      await commander
        .getByTestId('recipient-picker')
        .locator('li', { hasText: FIREFIGHTER.name })
        .getByRole('checkbox')
        .check();
      await commander.getByTestId('publish').click();
      await commander.getByRole('button', { name: 'Objavi', exact: true }).click();
      await expect(firefighter.getByRole('heading', { name: /prekid veze/ })).toBeVisible({
        timeout: REALTIME_BUDGET,
      });

      /*
       * Now take the socket away and change something while it is gone.
       *
       * This is the case Realtime cannot solve by itself: it does not replay.
       * The application's answer is a re-read on resume and a timer while the
       * socket is down, and this is the test of both - the firefighter's screen
       * is never navigated or refreshed by hand.
       */
      project.cutRealtime();
      await expect(firefighter.getByTestId('live-state')).toHaveAttribute(
        'data-live', 'POLLING', { timeout: 30_000 },
      );

      await commander.getByRole('tab', { name: 'Poziv' }).click();
      await commander.getByTestId('status-DEPLOYED').click();

      // Only the fallback can deliver this, and it must. Twelve seconds plus a
      // margin - deliberately longer than REALTIME_BUDGET, because this is the
      // slow path and pretending otherwise would hide a real regression.
      await expect(
        firefighter.getByText(/Na terenu/).first(),
        'an event missed while the socket was down must still arrive',
      ).toBeVisible({ timeout: 30_000 });
    } finally {
      await pair.close();
    }
  });

  test('a change notice is never treated as permission to show anything', async ({ browser }) => {
    const pair = await twoPeople(browser);
    const { commander, firefighter, project } = pair;
    const MARKER = 'TAJNI-SADRZAJ-KOJI-SE-NE-SMIJE-VIDJETI';

    try {
      await bothLive(pair);

      /*
       * A payload the firefighter must not see, pushed straight down their own
       * subscribed socket.
       *
       * `useLiveOperations` is built on one rule: a notice means "something may
       * have moved", never "here is the thing". If that rule holds, the marker
       * cannot reach the screen no matter what arrives - the hook re-reads
       * through the ordinary policy-checked query and renders that instead.
       */
      project.leakAttempt(MARKER);
      await firefighter.waitForTimeout(2_000);

      await expect(
        firefighter.locator('body'),
        'a realtime payload must never be rendered',
      ).not.toContainText(MARKER);

      // And the screen is still working - this is not passing because it broke.
      await expect(firefighter.getByTestId('live-state')).toHaveAttribute('data-live', 'LIVE');

      // The commander's screen is not a leak either: the private intervention
      // exists in the store and the firefighter's reads never return it.
      await expect(commander.locator('body')).not.toContainText(MARKER);
      await expect(firefighter.locator('body')).not.toContainText('Interna priprema');
    } finally {
      await pair.close();
    }
  });

  test('one screen opens one channel, however often it re-renders', async ({ browser }) => {
    const pair = await twoPeople(browser);
    const { commander, project } = pair;

    try {
      await bothLive(pair);
      // Two screens, two contexts, two channels. A third would mean a render
      // loop is opening a subscription it never closes.
      expect(project.socketCount(), 'one channel per open screen').toBe(2);

      // Force a burst of re-renders by typing, which is what the old duplicate
      // subscription bug was reached through.
      for (const text of ['a', 'ab', 'abc', 'abcd']) {
        await commander.getByTestId('new-title').fill(text);
      }
      await commander.waitForTimeout(1_000);
      expect(project.socketCount(), 'typing must not open a second channel').toBe(2);
    } finally {
      await pair.close();
    }
  });
});

test.describe('the two sessions really are independent', () => {
  test('neither context can see the other’s stored session', async ({ browser }) => {
    /*
     * The assertion that makes every other test in this file mean something.
     *
     * If these were two tabs of one browser they would share `localStorage` and
     * one Supabase session, and "two people" would be one person twice. This
     * reads the stored session key out of each context and requires them to
     * name different accounts.
     */
    const pair = await twoPeople(browser);
    try {
      const read = async (page: Page) =>
        page.evaluate(() => {
          const key = Object.keys(window.localStorage).find((k) => k.endsWith('-auth-token'));
          return key === undefined ? null : window.localStorage.getItem(key);
        });

      const a = await read(pair.commander);
      const b = await read(pair.firefighter);
      expect(a, 'context A must hold a session').not.toBeNull();
      expect(b, 'context B must hold a session').not.toBeNull();
      expect(a).toContain(COMMANDER.userId);
      expect(b).toContain(FIREFIGHTER.userId);
      expect(a, 'two contexts must not share one session').not.toBe(b);
      expect(a).not.toContain(FIREFIGHTER.userId);
      expect(b).not.toContain(COMMANDER.userId);

      // And the server agrees about who each of them is.
      await expect(pair.commander.locator('.identity-pill__role')).toContainText('COMMANDER');
      await expect(pair.firefighter.locator('.identity-pill__role')).toContainText('FIREFIGHTER');
      expect(COMMANDER_MEMBER).not.toBe(FIREFIGHTER_MEMBER);
    } finally {
      await pair.close();
    }
  });
});
