-- ===========================================================================
-- HISTORICAL NOTE ONLY — THIS FILE CONTAINS NO EXECUTABLE SQL.
--
-- Do not use this file to change pg_net privileges. Supabase Support confirmed
-- on 2026-10-09 that individual projects cannot modify pg_net grants. The
-- extension is created by supabase_admin; the project owner's postgres role
-- cannot revoke grants issued by that role, and the PUBLIC grants are required
-- by Supabase platform services. Support applies them again on extension
-- creation and may reapply them during major Postgres upgrades or when Database
-- Webhooks are enabled.
--
-- The previous version contained REVOKE/GRANT statements even though running
-- them as the project owner did not change the grants. Running them with a
-- privileged platform role could break pg_cron, Database Webhooks, or pg_net.
-- Those statements have been removed so this file is safe to inspect or run.
--
-- PUBLIC's pg_net grants mean every direct database login can interact with
-- the request queue and worker. Do not create the proposed dump login while
-- these grants remain. scripts/restored-capture/privileges.mjs intentionally
-- keeps verify-role fail-closed. See docs/RESTORED_CAPTURE_REHEARSAL.md.
-- ===========================================================================
